version: "3.7"

services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 5432
    expose:
      - 5432
    ports:
      - "5431:5432"
    env_file:
      - .env
    networks:
      - custom
    
  app:
    build:
      context: .
    container_name: project_bot
    command: ["/bot/bot/start.sh"]
    depends_on:
      - db
    networks:
      - custom
      

networks:
  custom:
    driver: bridge